apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
data:
  trigger.on-sync-succeeded: |
    - description: Application syncing has succeeded
      send:
      - app-sync-succeeded
      when: app.status.operationState != nil and app.status.operationState.phase in ['Succeeded']
  template.app-sync-succeeded: |
    email:
      subject: Application {{.app.metadata.name}} has been successfully synced.
    message: |
      {{if eq .serviceType "slack"}}:white_check_mark:{{end}} Application {{.app.metadata.name}} has been successfully synced at {{.app.status.operationState.finishedAt}}.
      Sync operation details are available at: {{.context.argocdUrl}}/applications/{{.app.metadata.name}}?operation=true . 
    slack:
      attachments: |
        [
        {
          "mrkdwn_in": ["text", "fields"],
          "text": "*Application:* {{ .app.metadata.name}}\n",
          "color": "#18be52",
          "fields": [
          {
            "title": "Sync status:",
            "value": "{{.app.status.sync.status}}",
            "short": true
          },

          {
            "title": "Revision:",
            "value": "{{.app.status.sync.revision}}",
            "short": true
          },
          {
            "title": "Operation initiated by:",
            "value": "*username:* {{.app.status.operationState.operation.initiatedBy.username}}\n*automated:* {{.app.status.operationState.operation.initiatedBy.automated}}", 
            "short": true 
          }
          ]
        },

        {
          "color": "#18be52",
          "fields": [
            {"title": "Resources updated:"}
            {{range $index, $c := .app.status.operationState.syncResult.resources}}
            {{if not $index}},{{end}}
            {{if $index}},{{end}}
            {
              "value": "+ {{$c.message}}\n",
              "short": true
            }
            {{end}} 
            ]
        },

        # new messages from here:

        {
          "color": "#18be52", 
          "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "*Application:* {{ .app.metadata.name}}\n"
                }
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "*Operation initiated by:* \n*username:* {{.app.status.operationState.operation.initiatedBy.username}}\n*automated:* {{.app.status.operationState.operation.initiatedBy.automated}}"
                }
              },
              
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "*Sync status:*\n {{.app.status.sync.status}}"
                }
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "*Revision:*\n {{.app.status.sync.revision}}"
                }
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "*Resources updated:*"
                }
              }

              {{range $index, $c := .app.status.operationState.syncResult.resources}}
              {{if not $index}},{{end}}
              {{if $index}},{{end}}
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "+ {{$c.message}}"
                }
              }
              {{end}}
            ]
          }      
        ]
      deliveryPolicy: Post
      groupingKey: ""
      notifyBroadcast: false
    teams:
      facts: |
        [{
          "name": "Sync Status",
          "value": "{{.app.status.sync.status}}"
        },
        {
          "name": "Synced at",
          "value": "{{.app.status.operationState.finishedAt}}"
        },
        {
          "name": "Operation Status"",
          "value": "{{.app.status.operationState.finishedAt}}"
        },
        {
          "name": "Repository",
          "value": "{{.app.spec.source.repoURL}}"
        }
        {{range $index, $c := .app.status.conditions}}
          {{if not $index}},{{end}}
          {{if $index}},{{end}}
          {
            "name": "_Kind: {{$c.kind}}_",
            "value": _Message: {{$c.message}}_
          }
        {{end}}
        ]
      potentialAction: |-
        [{
          "@type":"OpenUri",
          "name":"Operation Details",
          "targets":[{
            "os":"default",
            "uri":"{{.context.argocdUrl}}/applications/{{.app.metadata.name}}?operation=true"
          }]
        },
        {
          "@type":"OpenUri",
          "name":"Open Repository",
          "targets":[{
            "os":"default",
            "uri":"{{.app.spec.source.repoURL | call .repo.RepoURLToHTTPS}}"
          }]
        }]
      themeColor: '#000080'
      title: Application {{.app.metadata.name}} has been successfully synced
  service.slack: |
    token: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

